const pt = {
  nav: {
    experience: 'Experiência',
    projects: 'Projetos',
    about: 'Trajetória',
    skills: 'Tecnologias',
    contact: 'Vamos conversar',
    skip: 'Pular para o conteúdo',
    label: 'Navegação principal',
    home: 'Guilherme Peniche, início',
    open: 'Abrir menu',
    close: 'Fechar menu',
    language: 'Idioma',
    pt: 'Mudar para português',
    en: 'Switch to English',
  },
  hero: {
    eyebrow: 'SOFTWARE, DADOS E POSSIBILIDADES',
    role: ['Desenvolvedor Full Stack', 'com atuação em IA aplicada.'],
    description:
      'Desenvolvo sistemas corporativos, dashboards e aplicações com inteligência artificial. Da necessidade de negócio ao software em uso.',
    work: 'Conheça meu trabalho',
    resume: 'Ver currículo',
    location: 'Salvador, Bahia',
    areas: 'Áreas de atuação',
    building: 'EM CONSTRUÇÃO CONSTANTE',
    focus: '01 — ATUAÇÃO',
    board: ['Sistemas que conectam', 'pessoas e informação.'],
    ai: 'Inteligência Artificial',
    context: 'DESENVOLVIMENTO COM CONTEXTO',
    explore: 'Explore a trajetória',
  },
  experience: {
    eyebrow: '01 / EXPERIÊNCIA',
    title: ['Software no contexto', 'do trabalho real.'],
    intro:
      'Aplicações que apoiam a gestão pública e evoluem junto com as necessidades de quem as utiliza.',
    period: '2025 — ATUAL',
    institution: 'Secretaria de Relações Institucionais da Bahia',
    role: 'Desenvolvimento de sistemas',
    areas: [
      {
        title: 'Sistemas corporativos',
        text: 'Desenvolvimento, modernização e manutenção de aplicações para acompanhamento institucional e rotinas administrativas.',
      },
      {
        title: 'Dados e relatórios',
        text: 'Dashboards gerenciais, relatórios municipais e estaduais, modelagem e migração de dados com PostgreSQL e MySQL.',
      },
      {
        title: 'Da demanda à entrega',
        text: 'Análise de requisitos, construção de módulos para coordenadorias e correção de problemas em produção.',
      },
      {
        title: 'Novos caminhos em infraestrutura',
        text: 'Participações pontuais em infraestrutura, conectando a prática profissional aos estudos de arquitetura na AWS.',
      },
    ],
  },
  projects: {
    eyebrow: '02 / PROJETOS SELECIONADOS',
    title: ['Ideias que ganharam', 'forma e código.'],
    intro:
      'Uma seleção de aplicações, experimentos e pesquisa. Cada projeto, um problema diferente para resolver.',
    explore: 'Explorar projeto',
    code: 'Código',
    repository: 'Código no GitHub',
    other: 'Outros projetos e experimentos',
    viewCode: 'Ver código',
    more: 'Mais no GitHub',
  },
  about: {
    eyebrow: '03 / PESQUISA E TRAJETÓRIA',
    title: ['Curiosidade que', 'vira investigação.'],
    intro:
      'Sou bacharel em Ciência da Computação pela UNIJORGE. Minha trajetória conecta desenvolvimento de software, análise de dados e pesquisa aplicada em inteligência artificial.',
    body: 'Gosto de entender o problema por trás de cada demanda e transformar esse contexto em aplicações úteis. Hoje, amplio essa visão com estudos de cloud e participação em atividades de infraestrutura.',
    recognition: 'RECONHECIMENTO',
    award: 'Melhor trabalho',
    category: 'Tecnologias Digitais e Computação de Alto Desempenho',
    research:
      'Otimização de código para escalabilidade de agentes de Deep Reinforcement Learning',
    publication:
      'Pesquisa em processos industriais estocásticos. Publicação no Journal of Bioengineering, Technologies and Health em 2026.',
    read: 'Ler artigo publicado',
  },
  skills: {
    eyebrow: '04 / REPERTÓRIO',
    title: ['Tecnologia a serviço', 'de cada problema.'],
    intro:
      'Ferramentas utilizadas em projetos profissionais, pessoais e de pesquisa.',
    certified: 'CERTIFICAÇÃO OBTIDA',
    certification:
      'Fundamentos de serviços, segurança, arquitetura e custos na nuvem AWS.',
    credential: 'Ver credencial',
    evolving: 'EM EVOLUÇÃO',
    cloud: 'Infraestrutura e arquitetura em nuvem',
    learning:
      'Após a certificação Cloud Practitioner, preparação para AWS Certified Solutions Architect – Associate, conectada à experiência prática em infraestrutura.',
    continuous: 'Aprendizado contínuo',
  },
  contact: {
    eyebrow: '05 / PRÓXIMA CONVERSA',
    title: ['Tem um desafio', 'em mente?'],
    intro:
      'Vamos conversar sobre desenvolvimento, IA aplicada e oportunidades de construir algo útil.',
    location: 'SALVADOR, BAHIA · BRASIL',
    form: 'Formulário de contato',
    name: 'Seu nome',
    email: 'E-mail',
    subject: 'Assunto',
    message: 'Mensagem',
    namePlaceholder: 'Como posso chamar você?',
    emailPlaceholder: 'voce@exemplo.com',
    subjectPlaceholder: 'Sobre o que vamos conversar?',
    messagePlaceholder: 'Conte um pouco sobre sua ideia ou oportunidade.',
    sending: 'Enviando…',
    send: 'Enviar mensagem',
    privacy:
      'Seu nome e e-mail serão utilizados para responder a esta mensagem.',
    success: 'Mensagem recebida. Obrigado pelo contato!',
    failure:
      'Não foi possível enviar. Tente novamente ou use o e-mail ao lado.',
    connection:
      'Não foi possível confirmar o envio. Você também pode entrar em contato diretamente por e-mail.',
  },
  footer: {
    description: 'Software, dados e IA.',
    location: 'Salvador, Bahia',
    resume: 'Currículo',
  },
  case: {
    all: 'Todos os projetos',
    technologies: 'Tecnologias',
    repository: 'Ver repositório',
    publication: 'Ler publicação',
    context: 'Contexto',
    problem: 'O problema',
    contribution: 'Minha contribuição',
    developed: 'O que foi desenvolvido',
    outcome: 'Resultado e aprendizados',
    talk: 'Vamos falar sobre software?',
    contact: 'Entre em contato',
  },
  resume: {
    title: 'Currículo',
    back: 'Voltar ao portfólio',
    print: 'Imprimir / salvar em PDF',
    role: 'Desenvolvedor Full Stack · IA aplicada',
    location: 'Salvador, Bahia, Brasil',
    profile: 'Perfil',
    summary:
      'Bacharel em Ciência da Computação com atuação no desenvolvimento e modernização de sistemas corporativos, dashboards e aplicações web. Experiência em projetos de machine learning, automação e pesquisa em Deep Reinforcement Learning.',
    experience: 'Experiência profissional',
    institution: 'SERIN — Secretaria de Relações Institucionais da Bahia',
    period: 'Desenvolvimento de sistemas · 2025 — atual',
    duties: [
      'Desenvolvimento, modernização e manutenção de aplicações corporativas e módulos para coordenadorias.',
      'Dashboards e relatórios gerenciais para acompanhamento institucional municipal e estadual.',
      'Análise de requisitos, correção de problemas em produção e modelagem e migração de dados.',
      'Atuação com Laravel, Vue.js, Inertia.js, React, Next.js, PostgreSQL e MySQL.',
      'Participações pontuais em infraestrutura, alinhadas aos estudos de arquitetura em nuvem.',
    ],
    projects: 'Projetos e pesquisa',
    recognition: 'Reconhecimento',
    award:
      'Melhor trabalho em Tecnologias Digitais e Computação de Alto Desempenho no XI SIINTEC (2025). Artigo publicado no JBTH (2026).',
    education: 'Formação e desenvolvimento',
    degree: 'Bacharelado em Ciência da Computação',
    passed: 'Certificação obtida por exame.',
    credential: 'Ver credencial no Credly',
    preparing: 'Preparação para AWS Certified Solutions Architect – Associate.',
    technologies: 'Tecnologias',
  },
  visual: {
    concept: 'CONCEITO DO PROJETO',
    memory: 'MEMÓRIA',
    tools: 'FERRAMENTAS',
    transactions: 'TRANSAÇÕES → MODELO',
    fraud: ['Encontrar padrões.', 'Investigar anomalias.'],
    precision: 'Precisão',
    reinforcement: 'APRENDIZADO POR REFORÇO',
    research: ['Experimentar.', 'Otimizar. Escalar.'],
    agent: 'Agente',
    environment: 'Ambiente',
    rules: 'REGRAS DE NEGÓCIO',
    finance: ['Do aporte', 'à carteira.'],
    purchase: 'Compra',
    allocation: 'Rateio',
  },
  seo: {
    title: 'Guilherme Peniche | Full Stack & IA aplicada',
    description:
      'Desenvolvedor Full Stack com atuação em sistemas corporativos, dashboards e IA aplicada. Conheça projetos, experiência na SERIN e pesquisa premiada no SIINTEC.',
    imageRole: 'Desenvolvimento Full Stack & IA aplicada',
    imageFooter: 'Sistemas corporativos · Inteligência artificial · Pesquisa',
    portfolio: 'PORTFÓLIO',
  },
  notFound: {
    title: 'Página não encontrada',
    description:
      'O endereço pode ter mudado. Explore o portfólio para encontrar projetos e informações de contato.',
    back: 'Voltar ao início',
  },
}
const en: typeof pt = {
  nav: {
    experience: 'Experience',
    projects: 'Projects',
    about: 'About',
    skills: 'Skills',
    contact: 'Let’s talk',
    skip: 'Skip to content',
    label: 'Main navigation',
    home: 'Guilherme Peniche, home',
    open: 'Open menu',
    close: 'Close menu',
    language: 'Language',
    pt: 'Mudar para português',
    en: 'Switch to English',
  },
  hero: {
    eyebrow: 'SOFTWARE, DATA AND POSSIBILITIES',
    role: ['Full Stack Developer', 'working with applied AI.'],
    description:
      'I build business applications, dashboards and AI-powered software, translating business needs into working systems.',
    work: 'Explore my work',
    resume: 'View résumé',
    location: 'Salvador, Brazil',
    areas: 'Areas of work',
    building: 'ALWAYS BUILDING AND LEARNING',
    focus: '01 — FOCUS',
    board: ['Systems that connect', 'people and information.'],
    ai: 'Artificial Intelligence',
    context: 'SOFTWARE WITH PURPOSE',
    explore: 'Explore my experience',
  },
  experience: {
    eyebrow: '01 / EXPERIENCE',
    title: ['Software shaped by', 'real business needs.'],
    intro:
      'Applications that support public administration and evolve with the people who use them.',
    period: '2025 — PRESENT',
    institution:
      'Secretariat for Institutional Relations of the State of Bahia, Brazil',
    role: 'Software development',
    areas: [
      {
        title: 'Business applications',
        text: 'Developing, modernizing and maintaining applications for institutional coordination and administrative workflows.',
      },
      {
        title: 'Data and reporting',
        text: 'Management dashboards, municipal and state-level reporting, and data modeling and migration with PostgreSQL and MySQL.',
      },
      {
        title: 'From requirements to delivery',
        text: 'Gathering requirements, building modules for internal departments and resolving production issues.',
      },
      {
        title: 'Growing into infrastructure',
        text: 'Contributing to selected infrastructure tasks while studying cloud architecture on AWS.',
      },
    ],
  },
  projects: {
    eyebrow: '02 / SELECTED PROJECTS',
    title: ['Ideas brought to life', 'through code.'],
    intro:
      'A selection of applications, experiments and research. Each project explores a different problem.',
    explore: 'Explore project',
    code: 'Code',
    repository: 'Source code on GitHub',
    other: 'More projects and experiments',
    viewCode: 'View code',
    more: 'More on GitHub',
  },
  about: {
    eyebrow: '03 / RESEARCH AND BACKGROUND',
    title: ['Turning curiosity', 'into research.'],
    intro:
      'I hold a bachelor’s degree in Computer Science from UNIJORGE, Brazil. My work brings together software development, data analysis and applied AI research.',
    body: 'I enjoy understanding the problem behind a request and turning that context into useful applications. I am expanding this perspective through cloud studies and hands-on infrastructure tasks.',
    recognition: 'RECOGNITION',
    award: 'Best Paper Award',
    category: 'Digital Technologies and High Performance Computing',
    research:
      'Code optimization for scalable Deep Reinforcement Learning agents',
    publication:
      'Research into stochastic industrial processes. Published in the Journal of Bioengineering, Technologies and Health in 2026.',
    read: 'Read the published paper',
  },
  skills: {
    eyebrow: '04 / SKILLS',
    title: ['The right tools', 'for each problem.'],
    intro:
      'Technologies used across professional work, personal projects and research.',
    certified: 'CERTIFICATION EARNED',
    certification:
      'Foundations of AWS cloud services, security, architecture and costs.',
    credential: 'Verify credential',
    evolving: 'CONTINUING DEVELOPMENT',
    cloud: 'Infrastructure and cloud architecture',
    learning:
      'After earning the Cloud Practitioner certification, I am preparing for AWS Certified Solutions Architect – Associate alongside practical infrastructure experience.',
    continuous: 'Always learning',
  },
  contact: {
    eyebrow: '05 / LET’S CONNECT',
    title: ['Have a challenge', 'in mind?'],
    intro:
      'Let’s discuss software development, applied AI and opportunities to build something useful.',
    location: 'SALVADOR, BAHIA · BRAZIL',
    form: 'Contact form',
    name: 'Your name',
    email: 'Email',
    subject: 'Subject',
    message: 'Message',
    namePlaceholder: 'What should I call you?',
    emailPlaceholder: 'you@example.com',
    subjectPlaceholder: 'What would you like to discuss?',
    messagePlaceholder: 'Tell me about your idea or opportunity.',
    sending: 'Sending…',
    send: 'Send message',
    privacy: 'Your name and email will be used to reply to this message.',
    success: 'Message received. Thank you for getting in touch!',
    failure:
      'Unable to send your message. Please try again or use the email address shown here.',
    connection:
      'I could not confirm delivery. You can also get in touch directly by email.',
  },
  footer: {
    description: 'Software, data and AI.',
    location: 'Salvador, Brazil',
    resume: 'Résumé',
  },
  case: {
    all: 'All projects',
    technologies: 'Technologies',
    repository: 'View repository',
    publication: 'Read publication',
    context: 'Context',
    problem: 'The problem',
    contribution: 'My contribution',
    developed: 'What I built',
    outcome: 'Outcomes and lessons',
    talk: 'Let’s talk about software.',
    contact: 'Get in touch',
  },
  resume: {
    title: 'Résumé',
    back: 'Back to portfolio',
    print: 'Print / save as PDF',
    role: 'Full Stack Developer · Applied AI',
    location: 'Salvador, Bahia, Brazil',
    profile: 'Profile',
    summary:
      'Computer Science graduate working on business applications, dashboards and web application development and modernization. Project experience in machine learning, automation and Deep Reinforcement Learning research.',
    experience: 'Professional experience',
    institution:
      'SERIN — Secretariat for Institutional Relations, State of Bahia, Brazil',
    period: 'Software development · 2025 — present',
    duties: [
      'Develop, modernize and maintain business applications and modules for internal departments.',
      'Build management dashboards and reports to support municipal and state-level institutional coordination.',
      'Gather requirements, resolve production issues, and model and migrate data.',
      'Work with Laravel, Vue.js, Inertia.js, React, Next.js, PostgreSQL and MySQL.',
      'Contribute to selected infrastructure tasks while studying cloud architecture.',
    ],
    projects: 'Projects and research',
    recognition: 'Recognition',
    award:
      'Best Paper Award in Digital Technologies and High Performance Computing at the XI SIINTEC (2025). Published in JBTH (2026).',
    education: 'Education and professional development',
    degree: 'Bachelor’s degree in Computer Science',
    passed: 'Certification earned by passing the exam.',
    credential: 'Verify on Credly',
    preparing: 'Preparing for AWS Certified Solutions Architect – Associate.',
    technologies: 'Technologies',
  },
  visual: {
    concept: 'PROJECT CONCEPT',
    memory: 'MEMORY',
    tools: 'TOOLS',
    transactions: 'TRANSACTIONS → MODEL',
    fraud: ['Find patterns.', 'Detect anomalies.'],
    precision: 'Precision',
    reinforcement: 'REINFORCEMENT LEARNING',
    research: ['Experiment.', 'Optimize. Scale.'],
    agent: 'Agent',
    environment: 'Environment',
    rules: 'BUSINESS LOGIC',
    finance: ['From contributions', 'to a portfolio.'],
    purchase: 'Purchase',
    allocation: 'Allocation',
  },
  seo: {
    title: 'Guilherme Peniche | Full Stack Developer & Applied AI',
    description:
      'Full Stack Developer building business applications, dashboards and applied AI solutions. Explore my experience, projects, AWS certification and award-winning research.',
    imageRole: 'Full Stack Development & Applied AI',
    imageFooter: 'Business applications · Artificial intelligence · Research',
    portfolio: 'PORTFOLIO',
  },
  notFound: {
    title: 'Page not found',
    description:
      'This address may have changed. Explore the portfolio to find projects and contact information.',
    back: 'Back to home',
  },
}
export const copy = { pt, en }
